const leadSinger = (artist = "someone") => {
    console.log(`${artist} is the lead singer of Cold Play`);
}

leadSinger(); //someone is the lead singer...
leadSinger("Chris Martin") //Chris Martin is the lead singer ...